[theme]
name = "catppuccin-mocha"
author = "Catppuccin"

[colors]
Base = "#cdd6f4"
Dim = "#6c7086"
Accent = "#89b4fa"
Success = "#a6e3a1"
Warning = "#fab387"
Important = "#cba6f7"
AlertError = "#f38ba8"
