[theme]
name = "solarized-dark"
author = "Ethan Schoonover"

[colors]
Base = "#839496"
Dim = "#586e75"
Accent = "#268bd2"
Success = "#859900"
Warning = "#b58900"
Important = "#d33682"
AlertError = "#dc322f"
